export const dataDemoChatBox = [
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "I am number 1",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 12,
    content: "Where number 2?",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 21,
    content: "It's me",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 13,
    content: "What about number 3?",
  },
  {
    idUser: 3,
    img: "https://picsum.photos/300",
    alt: "so3",
    idMes: 11,
    content: "I'm here",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 14,
    content: "Number 4?",
  },
  {
    idUser: 4,
    img: "https://picsum.photos/400",
    alt: "so4",
    idMes: 11,
    content: "Me",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 11,
    content: "Oke, let's go",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "Call the roll",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "Number 1",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 11,
    content: "Number 2",
  },
  {
    idUser: 3,
    img: "https://picsum.photos/300",
    alt: "so3",
    idMes: 11,
    content: "Number 3",
  },
  {
    idUser: 4,
    img: "https://picsum.photos/400",
    alt: "so4",
    idMes: 11,
    content: "Number 4",
  },
];
