export const dataDemoChatBox = [
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "Tôi là số 1",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 12,
    content: "Số 2 đâu",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 21,
    content: "Tôi đây",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 13,
    content: "Còn số 3 đâu",
  },
  {
    idUser: 3,
    img: "https://picsum.photos/300",
    alt: "so3",
    idMes: 11,
    content: "Có số 3",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 14,
    content: "Ông số 4 nữa",
  },
  {
    idUser: 4,
    img: "https://picsum.photos/400",
    alt: "so4",
    idMes: 11,
    content: "Có tôi",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 11,
    content: "Đầy đủ rồi bắt đầu thôi",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "Vậy thì điểm danh",
  },
  {
    idUser: 1,
    img: "https://picsum.photos/100",
    alt: "so1",
    idMes: 11,
    content: "Tôi là số 1",
  },
  {
    idUser: 2,
    img: "https://picsum.photos/200",
    alt: "so2",
    idMes: 11,
    content: "Tôi là số 2",
  },
  {
    idUser: 3,
    img: "https://picsum.photos/300",
    alt: "so3",
    idMes: 11,
    content: "Tôi là số 3",
  },
  {
    idUser: 4,
    img: "https://picsum.photos/400",
    alt: "so4",
    idMes: 11,
    content: "Tôi là số 4",
  },
];
